apiVersion: v1
kind: Secret
metadata:
  name: dockerreg
  namespace: dev
  creationTimestamp: '2021-11-01T11:16:27Z'
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJkb2NrZXJyZXBvLmljZWNhc2gubW9iaTo1MDAwIjp7InVzZXJuYW1lIjoiamVua2lucyIsInBhc3N3b3JkIjoiTzNzZzF2bnl3eHpVblhMIiwiYXV0aCI6ImFtVnVhMmx1Y3pwUE0zTm5NWFp1ZVhkNGVsVnVXRXc9In19fQ==
type: kubernetes.io/dockerconfigjson
