apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-fbc-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: test-zw-fbc.digittal.mobi
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-fbc-service
                port:
                  number: 8588
