apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
data:
  mariadb.username: cm9vdA==
  mariadb.password: R2FqSldhTG9zVnJUelk1UU9BcGs=
  tidb.username: cm9vdA==
  tidb.password: MFo3WV81eCJPcDZXJA==
  mongodb.username: cm9vdA==
  mongodb.password: ckxDY0xuM0p2OQ==
  auth.keycloak.admin.client-id: YWRtaW4tY2xp
  auth.keycloak.admin.client-secret: M1hLWjZWS0xCMzR2T0s5aEhucDliU1hFdFd3NlRzSTM=
  auth.keycloak.backoffice.admin.client-id: YWRtaW4tY2xp
  auth.keycloak.backoffice.admin.client-secret: alFvblV2eDJGQ0J3ajhNOGhGdDE4aGtoS1BoYW82OFc=
  legacy-db.username: Q29uY2VydG8=
  legacy-db.password: YzBuYzNydDA=
  minio.access-name: YWRtaW4=
  minio.access-secret: NkNyeEx4Y0hNVQ==
  ecocash.http-auth-user: aWNlbWVic2Z0              # UAT
  ecocash.http-auth-pass: IWMzY0A1aG1FY2h0          # UAT
#  ecocash.http-auth-user: SUNFTUVCU1BU              # PROD
#  ecocash.http-auth-pass: MUMjM3o4cHdAaQ==          # PROD
  flexcube.user: aWNlY2FzaA==
  flexcube.password: cGFzc3dvcmQ=                 # UAT
#  flexcube.password: N1lDdzl6STI5b1RRN1ZQU1NrWW9lbi9VaUYrdkd3eFR1Ym1ZN2h2SEQ0az0=
  spring.data.redis.password: WnVRQ2RrUkJwOA==
  ice.cash.ip-whitelist.password: cEBzc3cwcmQx