apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-moz-customer-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: test-mz-customer.digittal.mobi
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-moz-customer
                port:
                  number: 8881
