apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-backoffice-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: test-mz-backoffice.digittal.mobi
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-backoffice
                port:
                  number: 8882
