server:
  port: 8286
  shutdown: graceful
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  devtools:
    livereload:
      enabled: false
ice:
  cash:
    ecocash:
      group: ${kafka.prefix}.ecocash-service
      payment-url: https://payonline.econet.co.zw/ecocashGateway-preprod/payment/v1/transactions/amount
      payment-status-url: https://payonline.econet.co.zw/ecocashGateway-preprod/payment/v1/%s/transactions/amount/%s
      refund-url: https://payonline.econet.co.zw/ecocashGateway-preprod/payment/v1/transactions/refund
      notify-url-host: http://localhost:8286
      http-auth-user: ${ecocash.http-auth-user}
      http-auth-pass: ${ecocash.http-auth-pass}
      phone-expression: (\+?263|0)?(77|78)\d{7}
      request-country-code: ZW
      request-location: 77 Coventry Road Harare
      request-super-merchant-name: ICEcash
      request-merchant-name: ICEcash
      payment-amount-channel: WEB
      payment-amount-purchase-category-code: Online Payment
      payment-amount-on-behalf-of: Paynow Topup
      status-poll-ms: 5000
      status-poll-init-delay: 5
      status-poll-timeout: 35
      cleanup-history-cron: "0 0 0 * * ?"
      cleanup-history-older-days: 365
      expired-payments-recheck: "true"
      expired-payments-recheck-ms: 5000
      expired-payments-recheck-after: 900
      simulate-response:
        "770000000": COMPLETED
        "770000001": FAILED
        "770000002": TRANSACTION TIMED OUT
ecocash:
  http-auth-user: "icemebsft"
  http-auth-pass: "!c3c@5hmEcht"
---
spring.config.activate.on-profile: prod-k8s
ice:
  cash:
    ecocash:
      payment-url: https://payonline.econet.co.zw/ecocashGateway/payment/v1/transactions/amount
      payment-status-url: https://payonline.econet.co.zw/ecocashGateway/payment/v1/%s/transactions/amount/%s
      refund-url: https://payonline.econet.co.zw/ecocashGateway/payment/v1/transactions/refund
