apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-mpesa-service
  name: payments-mpesa-service
spec:
  ports:
    - name: "8589"
      port: 8589
      targetPort: 8289
  selector:
    app: payments-mpesa-service
  type: ClusterIP
