apiVersion: v1
kind: Secret
metadata:
  name: payments-secret-zim
type: Opaque
data:
  legacy-db.username: Q29uY2VydG8=
  legacy-db.password: YzBuYzNydDA=
  mongodb.username: cm9vdA==
  mongodb.password: ckxDY0xuM0p2OQ==
