apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: "8280"
      port: 8280
      targetPort: 8080
  selector:
    app: kafka-ui
  type: ClusterIP
