apiVersion: v1
kind: Secret
metadata:
  name: payments-secret-zim
type: Opaque
data:
  legacy-db.username: Q29uY2VydG8=
  legacy-db.password: YzBuYzNydDA=
  mongodb.username: cm9vdA==
  mongodb.password: ckxDY0xuM0p2OQ==
  ecocash.http-auth-user: aWNlbWVic2Z0              # UAT
  ecocash.http-auth-pass: IWMzY0A1aG1FY2h0          # UAT
#  ecocash.http-auth-user: SUNFTUVCU1BU              # PROD
#  ecocash.http-auth-pass: MUMjM3o4cHdAaQ==          # PROD
  flexcube.user: aWNlY2FzaA==
  flexcube.password: cGFzc3dvcmQ=                 # UAT
#  flexcube.password: N1lDdzl6STI5b1RRN1ZQU1NrWW9lbi9VaUYrdkd3eFR1Ym1ZN2h2SEQ0az0=
  spring.data.redis.password: WnVRQ2RrUkJwOA==
  ice.cash.fbc.username: aWNlY2FzaA==
  ice.cash.fbc.password: aWNlY2FzaDEyMyo=
  ice.cash.ip-whitelist.password: cEBzc3cwcmQx
