apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-api-service
  name: payments-api-service
spec:
  ports:
    - name: "8581"
      port: 8581
      targetPort: 8281
  selector:
    app: payments-api-service
  type: ClusterIP
