apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-ecocash-service
  name: payments-ecocash-service
spec:
  ports:
    - name: "8586"
      port: 8586
      targetPort: 8286
  selector:
    app: payments-ecocash-service
  type: ClusterIP
