apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-ledger-service
  name: payments-ledger-service
spec:
  ports:
    - name: "8584"
      port: 8584
      targetPort: 8284
  selector:
    app: payments-ledger-service
  type: ClusterIP
