apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-paygo-service
  name: payments-paygo-service
spec:
  ports:
    - name: "8585"
      port: 8585
      targetPort: 8285
  selector:
    app: payments-paygo-service
  type: ClusterIP
