apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
data:
  mariadb.username: cm9vdA==
  mariadb.password: R2FqSldhTG9zVnJUelk1UU9BcGs=
  mongodb.username: cm9vdA==
  mongodb.password: ckxDY0xuM0p2OQ==
  auth.keycloak.admin.client-id: YWRtaW4tY2xp
  auth.keycloak.admin.client-secret: SXpUWE1DRmJvd3J4WkhEQnBFV01pR1RSSHgxSWxXVm0=
  legacy-db.username: Q29uY2VydG8=
  legacy-db.password: YzBuYzNydDA=
  minio.access-name: cGF2bG9z
  minio.access-secret: cTdrOVdIRUFGYklxMjAxMU1uMFo=
  ecocash.http-auth-user: aWNlbWVic2Z0              # UAT
  ecocash.http-auth-pass: IWMzY0A1aG1FY2h0          # UAT
#  ecocash.http-auth-user: SUNFTUVCU1BU              # PROD
#  ecocash.http-auth-pass: MUMjM3o4cHdAaQ==          # PROD
  flexcube.user: aWNlY2FzaA==
  flexcube.password: cGFzc3dvcmQ=                 # UAT
#  flexcube.password: N1lDdzl6STI5b1RRN1ZQU1NrWW9lbi9VaUYrdkd3eFR1Ym1ZN2h2SEQ0az0=
  spring.redis.password: aTdhQktsV2V3Vw==
  ice.cash.ip-whitelist.password: cEBzc3cwcmQx