apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-sync-service
  name: payments-sync-service
spec:
  ports:
    - name: "8582"
      port: 8582
      targetPort: 8282
  selector:
    app: payments-sync-service
  type: ClusterIP
