apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-zim-api-service
  name: payments-zim-api-service
spec:
  ports:
    - name: "8592"
      port: 8592
      targetPort: 8292
  selector:
    app: payments-zim-api-service
  type: ClusterIP
