apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-zim-api-ingress
  namespace: uat
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: uat-zw-api.icecash.mobi
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-zim-api-service
                port:
                  number: 8592
          - path: /ecocash/api/callback
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-ecocash-service
                port:
                  number: 8586
