server:
  port: 8284
  shutdown: graceful
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  devtools:
    livereload:
      enabled: false
ice:
  cash:
    ledger:
      group: ${kafka.prefix}.ledger-service
      balance-audit-asynchronous: true
---
spring.config.activate.on-profile: local,local-perf,local-docker
balance-warning-email:
  from: balance.alert@ice.cash
  subject: "*** TEST wrong balance alert ***"
  body: "<html><p>Wrong balance found for account: %s, expected: %s, actual: %s</p></html>"
  recipients: Pavlo <pavlo@ice.cash>
